app_louvre:
    resource: "@AppLouvreBundle/Resources/config/routing.yml"
    prefix:   /

app_louvre_translation:
    path:    /traduction/{name}
    defaults: { _controller: AppLouvreBundle:App:translation }
