services:
    app_louvre.orderCode:
        class: App\LouvreBundle\Services\OrderCode

    app_louvre.rate:
        class: App\LouvreBundle\Services\TicketsRate

    app_louvre.limit:
        class: App\LouvreBundle\Services\ValidLimit

    app_louvre.time:
        class: App\LouvreBundle\Services\ValidTime
        
    app_louvre.email:
        class: App\LouvreBundle\Services\ApplicationMailer        
